/* Level data for Pengi's Ice Slide.
 * par = optimal number of moves, computed by tools/solve.js — do not guess.
 *
 * Legend: P start, G igloo, F fish, # ice block, C cracked ice, O hole, . ice
 */
const LEVELS = [
  {
    name: 'First Slide',
    hint: 'Swipe to slide. Pengi only stops when he hits something!',
    par: 1,
    map: [
      '.....',
      '.....',
      'P...G',
      '.....',
      '.....',
    ],
  },
  {
    name: 'Cold Corner',
    hint: 'Two swipes to get home.',
    par: 2,
    map: [
      '......',
      '.....#',
      '......',
      'P.....',
      '......',
      '....G.',
    ],
  },
  {
    name: 'First Fish',
    hint: 'Grab every fish before heading to the igloo.',
    par: 2,
    map: [
      '......',
      '......',
      'P..F.#',
      '......',
      '....G.',
    ],
  },
  {
    name: 'Hole in One',
    hint: 'Dark water means a cold bath. Slide around it!',
    par: 3,
    map: [
      '......',
      '......',
      'P..O.G',
      '......',
      '......',
    ],
  },
  {
    name: 'Thin Ice',
    hint: 'Cracked ice breaks once you slide off it. No going back!',
    par: 4,
    map: [
      '.....',
      'G.#..',
      '.....',
      'P.C.F',
      '.....',
    ],
  },
  {
    name: 'Slalom',
    hint: 'Chain your slides together.',
    par: 3,
    map: [
      '.......',
      '..#...F',
      '......P',
      '.......',
      '....#..',
      '.......',
      'G......',
    ],
  },
  {
    name: 'Icebreaker',
    hint: 'Three fish in one grand loop.',
    par: 3,
    map: [
      'P...C..G',
      '........',
      '.#..O...',
      '....C...',
      'F...C..F',
      '........',
      '...#....',
      '.O....O.',
      '....F...',
    ],
  },
  {
    name: 'Long Way Home',
    hint: 'Sometimes the igloo is the last stop of a long trip.',
    par: 4,
    map: [
      '.....#.P',
      '.#....F.',
      '........',
      '...C....',
      'G.......',
      '...#....',
      '.F......',
      '......#.',
    ],
  },
  {
    name: 'Igloo Doorstop',
    hint: 'The igloo stops you even without the fish. Handy!',
    par: 5,
    map: [
      '...#.',
      '..G..',
      '.....',
      '.....',
      'P..F.',
    ],
  },
  {
    name: 'Crackle',
    hint: 'That cracked ice is a trap for careless penguins.',
    par: 5,
    map: [
      '.......',
      '.G#....',
      '#......',
      '..CCC..',
      '.......',
      '....#..',
      'P...F..',
    ],
  },
  {
    name: 'Around the Pond',
    hint: 'Mind the water on every side.',
    par: 6,
    map: [
      '.......',
      '.F.....',
      '...O...',
      '#..P...',
      '...O...',
      '.....F.',
      'G..#..#',
    ],
  },
  {
    name: 'Fish Market',
    hint: 'Three fish. Plan the whole loop before you swipe.',
    par: 6,
    map: [
      '.#...#.',
      '#F...F.',
      '.......',
      '.......',
      '...P...',
      '.......',
      '.......',
      '#F...G#',
    ],
  },
  {
    name: 'Switchback',
    hint: 'Back and forth and back again.',
    par: 6,
    map: [
      'P.#.....',
      '........',
      '.....#..',
      '..F.....',
      '#....O..',
      '........',
      '....#..F',
      '.C......',
      '........',
      '..G....#',
    ],
  },
  {
    name: 'Broken Bridge',
    hint: 'Each bridge crossing is one-way.',
    par: 6,
    map: [
      'P..#...#',
      '........',
      '##CC####',
      '..F..#..',
      '####CC##',
      '........',
      '#.......',
      'G.....F.',
    ],
  },
  {
    name: 'Double Snack',
    hint: 'Two fish, one clever route.',
    par: 7,
    map: [
      '.......',
      '.F#....',
      '#......',
      'P.....F',
      '.......',
      '...#...',
      '......G',
    ],
  },
  {
    name: 'Cross Currents',
    hint: 'A minefield of holes. Thread the needle.',
    par: 7,
    map: [
      'P....#..',
      '..O..O..',
      '........',
      '.O..F.O.',
      '....#...',
      '.O....O.',
      '...F....',
      '#.O..O..',
      '.......G',
    ],
  },
  {
    name: 'The Vault',
    hint: 'The fish are locked away. Find the key slides.',
    par: 8,
    map: [
      '...#....',
      '.F...O.P',
      '....#...',
      '..#..C..',
      '........',
      '.O...#..',
      '...F....',
      '#.......',
      '....G..F',
    ],
  },
  {
    name: 'Deep Freeze',
    hint: 'Everything you have learned, all at once.',
    par: 8,
    map: [
      '....#..P',
      '.O......',
      '...F....',
      '......#.',
      '.#.#.C..',
      '........',
      '..O....F',
      '........',
      'F...#...',
      '.......G',
    ],
  },
  {
    name: "King's Court",
    hint: 'Four fish for the royal table.',
    par: 8,
    map: [
      '.#....#.',
      '#F....F.',
      '........',
      '...#....',
      'P.......',
      '.....O..',
      '..C.....',
      '........',
      '#F....F.',
      '....G.##',
    ],
  },
  {
    name: 'Crown Jewel',
    hint: 'A puzzle fit for a king. Good luck, Pengi!',
    par: 12,
    map: [
      '.....#..',
      '.F#.....',
      '#.....F.',
      '..#.....',
      'P.......',
      '.......#',
      '..F.....',
      '.....#..',
      '........',
      '...G....',
    ],
  },
];

if (typeof module !== 'undefined') module.exports = LEVELS;
