/* Level data for Pengi's Ice Slide.
 * par = optimal number of moves, computed by tools/solve.js — do not guess.
 *
 * Legend: P start, G igloo, F fish, # ice block, C cracked ice, O hole, . ice
 */
const LEVELS = [
  {
    name: 'First Slide',
    hint: 'Swipe to slide. Pengi only stops when he hits something!',
    par: 1,
    map: [
      '.....',
      '.....',
      'P...G',
      '.....',
      '.....',
    ],
  },
  {
    name: 'Cold Corner',
    hint: 'Two swipes to get home.',
    par: 2,
    map: [
      '......',
      '.....#',
      '......',
      'P.....',
      '......',
      '....G.',
    ],
  },
  {
    name: 'First Fish',
    hint: 'Grab every fish before heading to the igloo.',
    par: 2,
    map: [
      '......',
      '......',
      'P..F.#',
      '......',
      '....G.',
    ],
  },
  {
    name: 'Hole in One',
    hint: 'Dark water means a cold bath. Slide around it!',
    par: 3,
    map: [
      '......',
      '......',
      'P..O.G',
      '......',
      '......',
    ],
  },
  {
    name: 'Thin Ice',
    hint: 'Cracked ice breaks once you slide off it. No going back!',
    par: 4,
    map: [
      '.....',
      'G.#..',
      '.....',
      'P.C.F',
      '.....',
    ],
  },
  {
    name: 'Slalom',
    hint: 'Chain your slides together.',
    par: 3,
    map: [
      '.......',
      '..#...F',
      '......P',
      '.......',
      '....#..',
      '.......',
      'G......',
    ],
  },
  {
    name: 'Icebreaker',
    hint: 'Three fish in one grand loop.',
    par: 3,
    map: [
      'P...C..G',
      '........',
      '.#..O...',
      '....C...',
      'F...C..F',
      '........',
      '...#....',
      '.O....O.',
      '....F...',
    ],
  },
  {
    name: 'Long Way Home',
    hint: 'Sometimes the igloo is the last stop of a long trip.',
    par: 4,
    map: [
      '.....#.P',
      '.#....F.',
      '........',
      '...C....',
      'G.......',
      '...#....',
      '.F......',
      '......#.',
    ],
  },
  {
    name: 'Igloo Doorstop',
    hint: 'The igloo stops you even without the fish. Handy!',
    par: 5,
    map: [
      '...#.',
      '..G..',
      '.....',
      '.....',
      'P..F.',
    ],
  },
  {
    name: 'Crackle',
    hint: 'That cracked ice is a trap for careless penguins.',
    par: 5,
    map: [
      '.......',
      '.G#....',
      '#......',
      '..CCC..',
      '.......',
      '....#..',
      'P...F..',
    ],
  },
  {
    name: 'Around the Pond',
    hint: 'Mind the water on every side.',
    par: 6,
    map: [
      '.......',
      '.F.....',
      '...O...',
      '#..P...',
      '...O...',
      '.....F.',
      'G..#..#',
    ],
  },
  {
    name: 'Fish Market',
    hint: 'Three fish. Plan the whole loop before you swipe.',
    par: 6,
    map: [
      '.#...#.',
      '#F...F.',
      '.......',
      '.......',
      '...P...',
      '.......',
      '.......',
      '#F...G#',
    ],
  },
  {
    name: 'Switchback',
    hint: 'Back and forth and back again.',
    par: 6,
    map: [
      'P.#.....',
      '........',
      '.....#..',
      '..F.....',
      '#....O..',
      '........',
      '....#..F',
      '.C......',
      '........',
      '..G....#',
    ],
  },
  {
    name: 'Broken Bridge',
    hint: 'Each bridge crossing is one-way.',
    par: 6,
    map: [
      'P..#...#',
      '........',
      '##CC####',
      '..F..#..',
      '####CC##',
      '........',
      '#.......',
      'G.....F.',
    ],
  },
  {
    name: 'Double Snack',
    hint: 'Two fish, one clever route.',
    par: 7,
    map: [
      '.......',
      '.F#....',
      '#......',
      'P.....F',
      '.......',
      '...#...',
      '......G',
    ],
  },
  {
    name: 'Cross Currents',
    hint: 'A minefield of holes. Thread the needle.',
    par: 7,
    map: [
      'P....#..',
      '..O..O..',
      '........',
      '.O..F.O.',
      '....#...',
      '.O....O.',
      '...F....',
      '#.O..O..',
      '.......G',
    ],
  },
  {
    name: 'The Vault',
    hint: 'The fish are locked away. Find the key slides.',
    par: 8,
    map: [
      '...#....',
      '.F...O.P',
      '....#...',
      '..#..C..',
      '........',
      '.O...#..',
      '...F....',
      '#.......',
      '....G..F',
    ],
  },
  {
    name: 'Deep Freeze',
    hint: 'Everything you have learned, all at once.',
    par: 8,
    map: [
      '....#..P',
      '.O......',
      '...F....',
      '......#.',
      '.#.#.C..',
      '........',
      '..O....F',
      '........',
      'F...#...',
      '.......G',
    ],
  },
  {
    name: "King's Court",
    hint: 'Four fish for the royal table.',
    par: 8,
    map: [
      '.#....#.',
      '#F....F.',
      '........',
      '...#....',
      'P.......',
      '.....O..',
      '..C.....',
      '........',
      '#F....F.',
      '....G.##',
    ],
  },
  {
    name: 'Crown Jewel',
    hint: 'A puzzle fit for a king. Good luck, Pengi!',
    par: 12,
    map: [
      '.....#..',
      '.F#.....',
      '#.....F.',
      '..#.....',
      'P.......',
      '.......#',
      '..F.....',
      '.....#..',
      '........',
      '...G....',
    ],
  },
  {
    name: 'Second Wind',
    hint: 'A fresh sheet of ice. Warm up those flippers!',
    par: 3,
    map: [
      '......',
      '...#..',
      'P....F',
      '......',
      '.#....',
      '....G.',
    ],
  },
  {
    name: 'One-Way Street',
    hint: 'Cracked ice only lets you cross once.',
    par: 3,
    map: [
      'P..C..F',
      '######.',
      '.......',
      '.#.....',
      'G......',
    ],
  },
  {
    name: 'Bumper Run',
    hint: 'Bounce between the blocks.',
    par: 5,
    map: [
      '.#.....',
      '.......',
      '..F..#.',
      'P......',
      '....#..',
      '.......',
      '.#...G.',
    ],
  },
  {
    name: 'Order Up',
    hint: 'Three fish, served in the right order.',
    par: 5,
    map: [
      'P..C...F',
      '........',
      '.#..#...',
      '...C....',
      'F.......',
      '.....#..',
      '..#...C.',
      'F....G..',
    ],
  },
  {
    name: 'Fish Ladder',
    hint: 'Climb down the ladder, rung by rung.',
    par: 6,
    map: [
      'P....',
      '....#',
      '.F...',
      '#....',
      '...F.',
      '....#',
      '.....',
      '..G..',
    ],
  },
  {
    name: 'Ring of Ice',
    hint: 'The igloo is ringed by cracked ice. Every crossing counts.',
    par: 6,
    map: [
      'P...#.#',
      '.......',
      '..CCC..',
      '..CGC..',
      '..CCC.#',
      '.#.....',
      'F.....F',
    ],
  },
  {
    name: 'Trapdoor',
    hint: "That cracked ice won't hold twice.",
    par: 6,
    map: [
      '....#..P',
      '........',
      '...C....',
      '#....O..',
      '......F.',
      '.FC.....',
      'G......#',
    ],
  },
  {
    name: 'Cold Shoulder',
    hint: 'Two fish, two cracked tiles, one route.',
    par: 7,
    map: [
      'P..#...',
      '.......',
      '..C.F..',
      '.#.....',
      '....C..',
      'F......',
      '...G..#',
    ],
  },
  {
    name: 'Four Corners',
    hint: 'A fish in every corner of the map.',
    par: 8,
    map: [
      'F...#...F',
      '.........',
      '..#...#..',
      '.........',
      '....P....',
      '.#.......',
      '......#..',
      '.........',
      'F...G...F',
    ],
  },
  {
    name: 'Icicle Maze',
    hint: 'Wind your way between the icicles.',
    par: 8,
    map: [
      'P.#.....',
      '.....#..',
      '.#..F...',
      '......#.',
      '..#.....',
      'F....#..',
      '...#...F',
      '.#......',
      '.....G.#',
    ],
  },
  {
    name: 'Splash Zone',
    hint: 'Dark water everywhere. Keep your feet dry.',
    par: 8,
    map: [
      'P....#..',
      '.O......',
      '...O.F..',
      '.O....O.',
      '...F..#.',
      '#......F',
      '.#......',
      '.......#',
      '......G.',
    ],
  },
  {
    name: 'Glacier',
    hint: 'A wide open sheet with fish tucked in the seams.',
    par: 8,
    map: [
      'P....#....',
      '..O.....#.',
      '..........',
      '.#.......#',
      '....C...#.',
      '.F.......F',
      '.#....O...',
      '......#..#',
      '.#......F.',
      '....G....#',
    ],
  },
  {
    name: 'The Moat',
    hint: 'Only one bridge leads into the castle.',
    par: 10,
    map: [
      'P.....#',
      '.......',
      '#.OOO..',
      '..OG...',
      '..OOO.#',
      '.F.....',
      '#.....F',
    ],
  },
  {
    name: 'Pinball Parlor',
    hint: 'Use the igloo as a bumper — more than once.',
    par: 10,
    map: [
      'P......#',
      '.....#..',
      '..#.....',
      '.......F',
      '.#......',
      '....#...',
      '.F......',
      '....#.G#',
    ],
  },
  {
    name: 'Snowplow',
    hint: 'A long haul. Clear the whole road.',
    par: 10,
    map: [
      'P..#........',
      '..O....#....',
      '..F....C..F.',
      '.#.....#...#',
      '....O.....#.',
      '.....G....F.',
    ],
  },
  {
    name: 'Royal Runaround',
    hint: "They don't call it a runaround for nothing.",
    par: 10,
    map: [
      '.#..F...#',
      'P........',
      '...#.....',
      '......C..',
      '.O...#...',
      'F........',
      '#...#..F.',
      '.#.....O#',
      '....G..#.',
    ],
  },
  {
    name: 'Midnight Sun',
    hint: 'No rest for a penguin under the midnight sun.',
    par: 13,
    map: [
      '....#....P',
      '.F......O.',
      '......#...',
      '..#....F..',
      '.....C....',
      '.O.......#',
      '...F...#..',
      '.#........',
      'G....#..F.',
    ],
  },
  {
    name: 'Frostbite',
    hint: 'Cold enough to bite. Plan every slide.',
    par: 15,
    map: [
      '#...#....P',
      '.F.....#..',
      '.........#',
      '.#...F....',
      '........C.',
      '..#....#..',
      '#F...#....',
      '#....O...F',
      '.#.#..#...',
      '....#G...#',
    ],
  },
  {
    name: 'Avalanche',
    hint: 'One long tumble of a puzzle. Hold on!',
    par: 17,
    map: [
      'P...#.....',
      '.......O.F',
      '..#......#',
      '.....#....',
      '.F...C....',
      '#.......#.',
      '..O...F...',
      '.#.......#',
      '......#.F.',
      '...G.....#',
    ],
  },
  {
    name: "Pengi's Peak",
    hint: 'The summit at last. Show them how a king slides!',
    par: 18,
    map: [
      'P...#....',
      '......O..',
      '..F......',
      '.....#...',
      '.#...C.F.',
      '.........',
      '...O....#',
      '.F....#..',
      '....#....',
      '#...G..F.',
    ],
  },
];

if (typeof module !== 'undefined') module.exports = LEVELS;
